- name: Install redis
  apt: name=redis-server state=present update_cache=yes

- name: Configure redis to allow external connections
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  notify: redis-server restart
